api = "0.4"

[buildpack]
  id = "paketo-community/pip"
  name = "Paketo Pip Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "120355ab3197f76c8811ce40537a5446ba107eaccd8efe18369e03698eb595f0"
    source = "https://files.pythonhosted.org/packages/b7/2d/ad02de84a4c9fd3b1958dc9fb72764de1aa2605a9d7e943837be6ad82337/pip-21.0.1.tar.gz"
    source_sha256 = "99bbde183ec5ec037318e774b0d8ae0a64352fe53b2c7fd630be1d07e94f41e5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.0.1_linux_noarch_any-stack_120355ab.tgz"
    version = "21.0.1"

  [[metadata.dependencies]]
    id = "pip"
    sha256 = "50a99319341c714ced49716cd973239bbf6935691542c52d12dea6598042b913"
    source = "https://files.pythonhosted.org/packages/de/62/77b8b1a9f9c710988e5a58c22a7cd025b63b204df57a6ea939d6d39da421/pip-21.1.tar.gz"
    source_sha256 = "a810bf07c3723a28621c29abe8e34429fa082c337f89aea9a795865416b66d3e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip_21.1_linux_noarch_any-stack_50a99319.tgz"
    version = "21.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
