
[buildpack]
id = "org.cloudfoundry.pip"
name = "Pip Buildpack"
version = "0.0.6"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "pip"
sha256 = "7bf48f9a693be1d58f49f7af7e0ae9fe29fd671cde8a55e6edca3581c4ef5796"
source = "https://files.pythonhosted.org/packages/c4/44/e6b8056b6c8f2bfd1445cc9990f478930d8e3459e9dbf5b8e2d2922d64d3/pip-9.0.3.tar.gz"
source_sha256 = ""
stacks = ["org.cloudfoundry.stacks.cflinuxfs2","org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/pip/pip-9.0.3-7bf48f9a.tar.gz"
version = "9.0.3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
